BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "TB_PRODUTOS" (
	"COD_PRO"	INTEGER NOT NULL UNIQUE,
	"NOME_PROD"	TEXT NOT NULL,
	"PRECO_UNIT"	NUMERIC NOT NULL,
	PRIMARY KEY("COD_PRO")
);
CREATE TABLE IF NOT EXISTS "TB_CLIENTES" (
	"ID"	INTEGER NOT NULL,
	"END_CLI"	TEXT NOT NULL,
	"NOME_CLI"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TB_VENDEDORES" (
	"ID"	INTEGER NOT NULL,
	"NOME_VEND"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TB_NOTAS_FISCAIS" (
	"COD_CLI"	INTEGER,
	"COD_VEND"	INTEGER,
	"NUM_NF"	INTEGER NOT NULL UNIQUE,
	"SERIE_NF"	TEXT NOT NULL,
	FOREIGN KEY("COD_CLI") REFERENCES "TB_CLIENTES"("ID"),
	PRIMARY KEY("NUM_NF")
);
CREATE TABLE IF NOT EXISTS "TB_ITENS_NOTAFISCAL" (
	"NUM_NF"	INTEGER,
	"COD_PROD"	INTEGER,
	"QNTD"	INTEGER NOT NULL,
	FOREIGN KEY("COD_PROD") REFERENCES "TB_PRODUTOS"("COD_PRO"),
	FOREIGN KEY("NUM_NF") REFERENCES "TB_NOTAS_FISCAIS"("NUM_NF"),
	PRIMARY KEY("NUM_NF","COD_PROD")
);
COMMIT;
